name: .NET Core

on: [pull_request]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Install Paket tool locally
      run: dotnet tool install paket --tool-path .paket
      
    - name: Paket Install
      run: .paket/paket install
    
    - name: Dotnet Restore
      run: dotnet restore
    
    - name: Dotnet Build Release
      run: dotnet build -c Release --no-restore
    
    - name: Apt-get Install Snappy & ZSTD (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y libsnappy-dev
        sudo apt-get install -y libzstd-dev
        
    - name: Install Snappy (MacOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        curl -X GET http://go-snappy.com/Snappy.zip --output snappy.zip
        unzip snappy.zip
        
    - name: Install Snappy (MacOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        curl -X GET https://codeload.github.com/facebook/zstd/tar.gz/v1.4.4 --output libz
        tar -xvf libz
        cd zstd-1.4.4
        make install
    
    - name: Run Unit Tests
      run: |
        cd tests/UnitTests
        dotnet test -c Release --no-build
